### ISSUE TITLE
Say What Audio clips are just noise

### ISSUE THREAD

**Issue by koppen152** [jkhartshorne/KidTalkIssues#10] opened 2020-08-02 19:52 UTC
I didn’t get any words in Say What? I just got clips of noise, silence, or a click. The “correct” transcriptions were either “click” or “do do do do”

I was expecting to hear clips of kids talking. 

IPhone 7, safari 13.6

**Comment by Abbyrosler** [comment] 2020-08-04 17:37
This happened to me too on Macbook Pro (version 10.13.6); macOS: High Sierra; Chrome 83

When I click play button, I hear no speech (sounds something like a muffled drum). The "correct" transcriptions were either "coffee", "light", or "" (nothing in the quotations). After a couple tries, the "submit guess" button does not work.

**Comment by parkerrobbins** [comment] 2020-08-05 15:37
Reproduced here as well. As @Abbyrosler said, sometimes the correct transcription was "", and other times it was "do do do do" or "clip" when clearly the clip was just background noise.

**Date**
2020-08-05

**Browser / OS / device (including version numbers)**
Google Chrome Version 84.0.4147.105 (Official Build) (64-bit), Ubuntu 18.04.4 LTS, Dell Latitude E7450

**Comment by Abbyrosler** [comment] 2020-08-07 13:10
This happened again on my other device. The correct transcriptions this time were "light", "click", or "".

Safari 13; iOS 13.5.1; iphone 8

**Comment by lorenachipstudio** [comment] 2020-08-08 12:48
@parkerrobbins @koppen152 @Abbyrosler We've found that this is because of the large volume of test clips the devs have added to test features, rather than a bug in the software. We will begin removing test clips to address this. As for the "submit guess button" issue, this is from a separate bug report and should be fixed on staging now.

**Closed as completed** 2020-08-10 01:46 UTC
