### ISSUE TITLE
Long clip uploaded in full buffers indefinitely after pressing submit

### ISSUE THREAD

**Issue by parkerrobbins** [jkhartshorne/KidTalkIssues#25] opened 2020-08-05 14:55 UTC
**Date**
2020-08-05

**Browser / OS / device (including version numbers)**
Google Chrome Version 84.0.4147.105 (Official Build) (64-bit), Ubuntu 18.04.4 LTS, Dell Latitude E7450

**What did you do?**
Uploaded a large MP4 (7m22s; 25.6 MB) to extract audio from. Audio extraction was quick and audio played completely.

**What did you expect to happen?**
I expected some lagging and buffering when I clicked _Submit Conversation_ but that it would eventually upload.

**What did happen?**
It has continued to buffer for over 10 minutes and never resolved.

**Visual Evidence (screenshots, videos, text)**
![kidtalk_video_file](https://user-images.githubusercontent.com/31826170/89428017-e8e1a180-d709-11ea-91e2-8027be5f93b2.png)

**Comment by lorenachipstudio** [comment] 2020-08-05 20:06
@parkerrobbins We'll take a look- thanks!

**Comment by lorenachipstudio** [comment] 2020-08-08 12:50
@parkerrobbins We tested this with 100+ MB MP4s and were unable to recreate this issue thus far. It is possible that this was related to a separate bug that has since been fixed on staging, so it's worth testing again to see if the issue is resolved on staging. It is also possible that there is some difference between that specific video upload vs others we've seen, so you may want to test with a separate video upload to see if that works. We will be launching iOS and Android native applications for KidTalk which will have better file and upload support than the current web app version. When released, these new versions of KidTalk are likely to resolve upload issues like this.

**Comment by jkhartshorne** [comment] 2020-08-10 20:58
@parkerrobbins - can you test this again?

**Comment by ythuang123** [comment] 2020-08-10 22:25
I've encountered this bug on staging. I made a long recording (~10 min) and I've been waiting 6 minutes for the converting screen to resolve (see below). I'm using: Chrome, Window 10 Enterprise v. 1909 (OS build 18563.959), ThinkPad X1 Carbon 4G
![image](https://user-images.githubusercontent.com/68764650/89837383-dc5caf00-db36-11ea-9ebf-db75910057c5.png)

**Comment by ythuang123** [comment] 2020-08-11 01:04
This might be closer to @parkerrobbins's original bug (the one I posted could be a separate one). I recorded a 24 minute clip since we've been inviting families to leave their devices on to record dinner. This took 15 minutes to convert but now it's been stuck in the uploading page for the last 10 minutes. I'm using: Chrome, Window 10 Enterprise v. 1909 (OS build 18563.959), ThinkPad X1 Carbon 4G.

![image](https://user-images.githubusercontent.com/68764650/89845637-01f4b300-db4d-11ea-80a2-18d7a889dde6.png)

**Comment by alexchippendale** [comment] 2020-08-11 01:58
@ythuang123 Thanks for the info, we're investigating this.

**Comment by parkerrobbins** [comment] 2020-08-11 14:25
@jkhartshorne @lorenachipstudio No, I can't reproduce this anymore with the original clip and or with a file over 100MB.

**Comment by parkerrobbins** [comment] 2020-08-13 14:58
@jkhartshorne @lorenachipstudio @alexchippendale 

Today, I did have this problem again. Same device, OS, and Chrome version as before. 

The clip was 400 sec long and the MP4 was only 14.3MB (so not even really that large). I waited 35 minutes before I finally couldn't watch it in my peripheral vision anymore and closed the window.

**Comment by SecondStreetDevelopment** [comment] 2020-08-13 15:27
Thanks @parkerrobbins 

I had a feeling you would still be able to reproduce this issue.  I'm working on it right now.

**Comment by SecondStreetDevelopment** [comment] 2020-08-13 19:30
I've just published a pull request which contains a fix for this issue.  We will let you know after it is reviewed and merged/published to the staging site.

**Comment by alexchippendale** [comment] 2020-08-18 22:49
@parkerrobbins This should be fixed on staging now. It still may take a minute or two, but shouldn't buffer indefinitely after pressing submit any longer. Note we are also building out a new flow for recording which should also alleviate some of the waiting times (though that part isn't deployed yet!). Please verify that you are able to submit without it buffering indefinitely when you get a chance. Thanks!

**Comment by parkerrobbins** [comment] 2020-08-19 14:11
@alexchippendale Confirmed! Thank you so much!

**Comment by jkhartshorne** [comment] 2020-08-19 17:22
@ythuang123 - can you please confirm that you haven't seen this bug since the fix?

**Comment by ythuang123** [comment] 2020-08-19 17:59
@jkhartshorne -- I haven't seen this issue since the fix for #2. Made a lot of recordings on my iPhone and Lenovo.

**Comment by jkhartshorne** [comment] 2020-09-03 14:47
I forget -- did we ever have a solution for previously-recorded recordings that are stuck in processing? Or did we give up on those? 

I've been only looking at staging for a long time, so didn't realize these were still stuck:

![Screen Shot 2020-09-03 at 10 44 34 AM](https://user-images.githubusercontent.com/6118115/92130480-c8713980-edd2-11ea-83d2-0c4d6e8f2f60.png)

**Comment by ythuang123** [comment] 2020-09-03 14:49
@jkhartshorne -- thanks for following up with this. They are still stuck on my scrapbook too.

**Comment by parkerrobbins** [comment] 2020-09-03 14:55
Yes, me too!

![image](https://user-images.githubusercontent.com/31826170/92131412-fa36d000-edd3-11ea-832a-7240aa26487a.png)

**Comment by alexchippendale** [comment] 2020-09-03 17:39
@jkhartshorne @ythuang123 Not for some previously-recorded recordings. We pushed fixes for new recordings so they don't get stuck in the same way, but some older ones had errors with the audio file itself in the upload process. This had to do with relatively obscure Google Cloud platform upload errors which we've since found alternative methods for. Some were stuck for other reasons, which have been unstuck. For the others we had been investigating whether the older audio files could be linked back to the "stuck" entries is the DB, but thus far it doesn't seem like they are (we're still looking but it's unlikely). 

@parkerrobbins Were the files you are posting about from before the production deploy or after?

**Comment by parkerrobbins** [comment] 2020-09-03 17:54
@alexchippendale From before, just like those of @jkhartshorne and @ythuang123.

**Comment by jkhartshorne** [comment] 2020-09-09 20:01
@alexchippendale @lorenachipstudio -- would it be correct to say that any of the stuck recordings from before the new production deploy are a lost cause, and we should just delete them on our end?

**Comment by alexchippendale** [comment] 2020-09-09 21:18
@jkhartshorne Yes I would say so, I would go ahead and delete the stuck recordings from before the new production deploy.

New recordings shouldn't run into the same upload issue. Though rare, if a newer recording gets stuck we should be able to unstick it (see recent comments in #2). This is because now if it one gets stuck, it's because it's "processed" flag needs to be updated, not an issue with the recording getting into the cloud platform.

**Closed as completed** 2020-09-28 17:30 UTC
